// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Tuvankienthuc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251029111634_AddGoal_LanHocCuoi_ChatLogs")]
    partial class AddGoal_LanHocCuoi_ChatLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tuvankienthuc.Models.ChatLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaDX")
                        .HasColumnType("int");

                    b.Property<int>("MaSV")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TraLoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaDX");

                    b.HasIndex("MaSV");

                    b.ToTable("ChatLogs");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.ChuDe", b =>
                {
                    b.Property<int>("MaCD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCD"));

                    b.Property<bool>("IsKienThucCoBan")
                        .HasColumnType("bit");

                    b.Property<int>("MaMH")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCD")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCD");

                    b.HasIndex("MaMH");

                    b.ToTable("ChuDes");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.DeXuat", b =>
                {
                    b.Property<int>("MaDX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDX"));

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaMH")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("MaSV")
                        .HasColumnType("int");

                    b.Property<string>("Nguon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDX");

                    b.HasIndex("MaMH");

                    b.HasIndex("MaSV");

                    b.ToTable("DeXuats");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.DeXuatChiTiet", b =>
                {
                    b.Property<int>("MaDX")
                        .HasColumnType("int");

                    b.Property<int>("MaKT")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<int>("RankIndex")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("MaDX", "MaKT");

                    b.HasIndex("MaKT");

                    b.ToTable("DeXuatChiTiets");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.KienThuc", b =>
                {
                    b.Property<int>("MaKT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKT"));

                    b.Property<int>("DoKho")
                        .HasColumnType("int");

                    b.Property<bool>("IsKienThucCoBan")
                        .HasColumnType("bit");

                    b.Property<int>("MaCD")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKT");

                    b.HasIndex("MaCD");

                    b.ToTable("KienThucs");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.KienThucSinhVien", b =>
                {
                    b.Property<int>("MaSV")
                        .HasColumnType("int");

                    b.Property<int>("MaKT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LanHocCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSV", "MaKT");

                    b.HasIndex("MaKT");

                    b.ToTable("KienThucSinhViens");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.MonHoc", b =>
                {
                    b.Property<int>("MaMH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMH"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMH");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.TaiLieu", b =>
                {
                    b.Property<int>("MaTL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTL"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiTL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaTL");

                    b.ToTable("TaiLieus");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.TaiLieuChuDe", b =>
                {
                    b.Property<int>("MaTL")
                        .HasColumnType("int");

                    b.Property<int>("MaCD")
                        .HasColumnType("int");

                    b.Property<short?>("OrderIndex")
                        .HasColumnType("smallint");

                    b.HasKey("MaTL", "MaCD");

                    b.HasIndex("MaCD");

                    b.ToTable("TaiLieuChuDe", (string)null);
                });

            modelBuilder.Entity("Tuvankienthuc.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("NamHoc")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.ChatLog", b =>
                {
                    b.HasOne("Tuvankienthuc.Models.DeXuat", "DeXuat")
                        .WithMany()
                        .HasForeignKey("MaDX")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tuvankienthuc.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeXuat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.ChuDe", b =>
                {
                    b.HasOne("Tuvankienthuc.Models.MonHoc", "MonHoc")
                        .WithMany("ChuDes")
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.DeXuat", b =>
                {
                    b.HasOne("Tuvankienthuc.Models.MonHoc", "MonHoc")
                        .WithMany("DeXuats")
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tuvankienthuc.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonHoc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.DeXuatChiTiet", b =>
                {
                    b.HasOne("Tuvankienthuc.Models.DeXuat", "DeXuat")
                        .WithMany("ChiTiets")
                        .HasForeignKey("MaDX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tuvankienthuc.Models.KienThuc", "KienThuc")
                        .WithMany()
                        .HasForeignKey("MaKT")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DeXuat");

                    b.Navigation("KienThuc");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.KienThuc", b =>
                {
                    b.HasOne("Tuvankienthuc.Models.ChuDe", "ChuDe")
                        .WithMany("KienThucs")
                        .HasForeignKey("MaCD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuDe");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.KienThucSinhVien", b =>
                {
                    b.HasOne("Tuvankienthuc.Models.KienThuc", "KienThuc")
                        .WithMany("KienThucSinhViens")
                        .HasForeignKey("MaKT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tuvankienthuc.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KienThuc");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.TaiLieuChuDe", b =>
                {
                    b.HasOne("Tuvankienthuc.Models.ChuDe", "ChuDe")
                        .WithMany()
                        .HasForeignKey("MaCD")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tuvankienthuc.Models.TaiLieu", "TaiLieu")
                        .WithMany()
                        .HasForeignKey("MaTL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuDe");

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.ChuDe", b =>
                {
                    b.Navigation("KienThucs");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.DeXuat", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.KienThuc", b =>
                {
                    b.Navigation("KienThucSinhViens");
                });

            modelBuilder.Entity("Tuvankienthuc.Models.MonHoc", b =>
                {
                    b.Navigation("ChuDes");

                    b.Navigation("DeXuats");
                });
#pragma warning restore 612, 618
        }
    }
}
